<?php
/**
 * @file
 * Code for the WIM RSS feature.
 */

include_once 'wim_rss.features.inc';

define('WIM_RSS_DEFAULT_HOMEBOX_PAGE', 'dashboard_intranet');

/**
 * Implements hook_block_info().
 */
function wim_rss_block_info() {
  $feeds = db_select('node', 'n')
    ->fields('n', array('nid', 'title'))
    ->condition('status', 1)
    ->condition('type', 'rss_source')
    ->execute();

  $blocks = array();

  foreach ($feeds as $feed) {
    $blocks[$feed->nid] = array(
      'info' => t('RSS Feed: !feed', array('!feed' => $feed->title)),
      'cache' => DRUPAL_NO_CACHE,
    );
  }

  return $blocks;
}

/**
 * Impelements hook_block_view().
 */
function wim_rss_block_view($delta) {
  $feed_node = node_load($delta);

  return array(
    'subject' => $feed_node->title,
    'content' => views_embed_view('rss_feeds', 'block_1', $feed_node->nid),
  );
}

/**
 * Implements hook_node_insert().
 */
function wim_rss_node_insert($node) {
  if ($node->type === 'rss_source') {
    _wim_rss_homebox_add($node);
    block_flush_caches();
  }
}

/**
 * Implements hook_node_update().
 */
function wim_rss_node_update($node) {
  if ($node->type === 'rss_source') {
    _wim_rss_homebox_add($node);
    block_flush_caches();
  }
}

/**
 * Implements hook_node_delete().
 */
function wim_rss_node_delete($node) {
  if ($node->type === 'rss_source') {
    _wim_rss_homebox_remove($node);
    block_flush_caches();
  }
}

/**
 * Helper function for adding a block to homebox.
 */
function _wim_rss_homebox_add($node) {
  if (module_exists('homebox')) {
    $page = homebox_get_page(variable_get('wim_rss_homebox_page', wim_rss_DEFAULT_HOMEBOX_PAGE));

    $page->settings['blocks']['wim_rss_' . $node->nid] = array(
      'module' => 'wim_rss',
      'delta' => $node->nid,
      'region' => 2,
      'movable' => 1,
      'status' => 1,
      'open' => 1,
      'closable' => 1,
      'title' => '',
      'weight' => 0,
    );

    homebox_save_page($page);
  }
}

/**
 * Helper function for removing a block from homebox.
 */
function _wim_rss_homebox_remove($node) {
  if (module_exists('homebox')) {
    $page = homebox_get_page(variable_get('wim_rss_homebox_page', wim_rss_DEFAULT_HOMEBOX_PAGE));
    unset($page->settings['blocks']['wim_rss-' . $node->nid]);
    homebox_save_page($page);
  }
}

/**
 * Implements hook_views_api().
 */
function wim_rss_views_api($module = NULL, $api = NULL) {
  return array('api' => '3.0');
}
