<?php
/**
 * @file
 * Custom tags module.
 */

/**
 * Implements hook_preprocess_html().
 */
function ckeditor_customtags_preprocess_html(&$variables) {
  global $theme;
  if ($theme === 'adminimal') {
    drupal_add_css(drupal_get_path('module', 'ckeditor_customtags') . '/ckeditor_customtags.adminimal.css', ['weight' => CSS_THEME]);
  }
}

/**
 * Implements hook_form_alter().
 */
function ckeditor_customtags_form_alter(&$form, &$form_state) {
  // TODO: Possibly make this less generic. The process function used to be
  // protected by a permission, although it's not entirely clear why. For now,
  // it just seems like another area for misconfiguration, so it has been
  // removed. Proceed with caution, though.
  $form['#after_build'][] = 'ckeditor_customtags_process_form';
}

/**
 * Function to be called after build for forms containing WYSIWYG Editor fields.
 */
function ckeditor_customtags_process_form(&$form, &$form_state) {
  static $added = FALSE;
  $js = drupal_add_js();
  if (!$added && isset($js['setting'])) {
    $setting = call_user_func_array('array_merge_recursive', $js['setting']);
    if (isset($setting['ckeditor']) || isset($setting['wysiwyg']['configs']['ckeditor'])) {
      drupal_add_js([
        'ckeditor_customtags' => [
          'module_path' => base_path() . drupal_get_path('module', 'ckeditor_customtags'),
        ],
      ], 'setting');
    }
    $added = TRUE;
  }
  return $form;
}

/**
 * Implements hook_wysiwyg_plugin().
 */
function ckeditor_customtags_wysiwyg_plugin($editor, $version) {
  if ($editor === 'ckeditor') {
    $path = drupal_get_path('module', 'ckeditor_customtags');
    $plugins['ckeditor_citebutton'] = [
      'path' => $path . '/plugins/cite',
      'filename' => 'cite.js',
      'buttons' => [
        'ckeditor_citebutton' => t('Cite'),
      ],
      'extensions' => [
        'ckeditor' => t('ckeditor'),
      ],
      'options' => [],
      'load' => TRUE,
      'internal' => FALSE,
      'extended_valid_elements' => [],
    ];

    $plugins['ckeditor_abbrbutton'] = [
      'path' => $path . '/plugins/abbr',
      'filename' => 'abbr.js',
      'buttons' => [
        'ckeditor_abbrbutton' => t('Abbreviation'),
      ],
      'extensions' => [
        'ckeditor' => t('ckeditor'),
      ],
      'options' => [],
      'load' => TRUE,
      'internal' => FALSE,
      'extended_valid_elements' => [],
    ];

    $plugins['ckeditor_acronym_button'] = [
      'path' => $path . '/plugins/acronym',
      'filename' => 'acronym.js',
      'buttons' => [
        'ckeditor_acronym_button' => t('Acronym'),
      ],
      'extensions' => [
        'ckeditor' => t('ckeditor'),
      ],
      'options' => [],
      'load' => TRUE,
      'internal' => FALSE,
      'extended_valid_elements' => [],
    ];

    $plugins['ckeditor_definitionlist_button'] = [
      'path' => $path . '/plugins/definitionlist',
      'filename' => 'definitionlist.js',
      'buttons' => [
        'ckeditor_definitionlist_button' => t('Definition List'),
      ],
      'extensions' => [
        'ckeditor' => t('ckeditor'),
      ],
      'options' => [],
      'load' => TRUE,
      'internal' => FALSE,
      'extended_valid_elements' => [],
    ];

    $plugins['ckeditor_insertionbutton'] = [
      'path' => $path . '/plugins/insertion',
      'filename' => 'insertion.js',
      'buttons' => [
        'ckeditor_insertionbutton' => t('Insertion'),
      ],
      'extensions' => [
        'ckeditor' => t('ckeditor'),
      ],
      'options' => [],
      'load' => TRUE,
      'internal' => FALSE,
      'extended_valid_elements' => [],
    ];

    $plugins['ckeditor_languagebutton'] = [
      'path' => $path . '/plugins/language',
      'filename' => 'language.js',
      'buttons' => [
        'ckeditor_languagebutton' => t('Language'),
      ],
      'extensions' => [
        'ckeditor' => t('ckeditor'),
      ],
      'options' => [],
      'load' => TRUE,
      'internal' => FALSE,
      'extended_valid_elements' => [],
    ];

    $plugins['ckeditor_deletionbutton'] = [
      'path' => $path . '/plugins/deletion',
      'filename' => 'deletion.js',
      'buttons' => [
        'ckeditor_deletionbutton' => t('Deletion'),
      ],
      'extensions' => [
        'ckeditor' => t('ckeditor'),
      ],
      'options' => [],
      'load' => TRUE,
      'internal' => FALSE,
      'extended_valid_elements' => [],
    ];

    $plugins['imagemaps'] = [
      'path' => $path . '/plugins/imagemaps',
      'filename' => 'plugin.js',
      'buttons' => [
        'imagemaps' => t('Image Maps'),
      ],
      'extensions' => [
        'ckeditor' => t('ckeditor'),
      ],
      'options' => [],
      'load' => TRUE,
      'internal' => FALSE,
      'extended_valid_elements' => [],
    ];

    if (file_exists('sites/all/libraries/ckeditor_plugins/a11ychecker/a11ychecker')) {
      $plugins['a11ychecker'] = [
        'path' => 'sites/all/libraries/ckeditor_plugins/a11ychecker/a11ychecker',
        'buttons' => [
          'A11ychecker' => t('Accessibility Checker'),
        ],
        'load' => TRUE,
        'internal' => FALSE,
      ];

      $plugins['balloonpanel'] = [
        'path' => 'sites/all/libraries/ckeditor_plugins/a11ychecker/balloonpanel',
        'extensions' => [
          'Balloonpanel' => t('Accessibility Checker GUI: Balloon panel'),
        ],
        'load' => TRUE,
        'internal' => FALSE,
      ];
    }

    return $plugins;
  }
}
