ReadSpeaker.lib||(ReadSpeaker.lib={});
(function(y,H){function u(x,a,d,c){for(var e=0,ca=a.length;e<ca;e++)m(x,a[e],d,c)}function a(x,a,d){var c=a.dir,ba=V++;x||(x=function(x){return x===d});return a.first?function(a,b){for(;a=a[c];)if(1===a.nodeType)return x(a,b)&&a}:function(a,b){for(var d,f=ba+"."+g,h=f+"."+e;a=a[c];)if(1===a.nodeType){if((d=a[v])===h)return a.sizset;if("string"===typeof d&&0===d.indexOf(f)){if(a.sizset)return a}else{a[v]=h;if(x(a,b))return a.sizset=!0,a;a.sizset=!1}}}}function c(x,a){return x?function(d,c){var e=a(d,
c);return e&&x(!0===e?d:e,c)}:a}var e,g,f,h,n,q=y.document,i=q.documentElement,A=!1,W=!0,V=0,C=[].slice,F=[].push,v=("sizcache"+Math.random()).replace(".",""),B="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("w","w#")+")|)|)[\\x20\\t\\r\\n\\f]*\\]",s="(?=[^\\x20\\t\\r\\n\\f])(?:\\\\.|"+B+"|"+":((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)(?:\\((?:(['\"])((?:\\\\.|[^\\\\])*?)\\2|((?:[^,]|\\\\,|(?:,(?=[^\\[]*\\]))|(?:,(?=[^\\(]*\\))))*))\\)|)".replace(2,
7)+"|[^\\\\(),])+",L=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),J=/^[\x20\t\r\n\f]*([\x20\t\r\n\f>+~])[\x20\t\r\n\f]*/,M=RegExp(s+"?(?=[\\x20\\t\\r\\n\\f]*,|$)","g"),X=RegExp("^(?:(?!,)(?:(?:^|,)[\\x20\\t\\r\\n\\f]*"+s+")*?|[\\x20\\t\\r\\n\\f]*(.*?))(\\)|$)"),da=RegExp(s.slice(19,-6)+"\\x20\\t\\r\\n\\f>+~])+|[\\x20\\t\\r\\n\\f]*([\\x20\\t\\r\\n\\f>+~])[\\x20\\t\\r\\n\\f]*","g"),ea=/^(?:#([\w\-]+)|(\w+)|\.([\w\-]+))$/,N=/[\x20\t\r\n\f]*[+~]/,fa=/:not\($/,ga=
/h\d/i,ha=/input|select|textarea|button/i,G=/\\(?!\\)/g,D={ID:/^#((?:\\.|[-\w]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[-\w]|[^\x00-\xa0])+)/,NAME:/^\[name=['"]?((?:\\.|[-\w]|[^\x00-\xa0])+)['"]?\]/,TAG:RegExp("^("+"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("[-","[-\\*")+")"),ATTR:RegExp("^"+B),PSEUDO:RegExp("^:((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)(?:\\((?:(['\"])((?:\\\\.|[^\\\\])*?)\\2|((?:[^,]|\\\\,|(?:,(?=[^\\[]*\\]))|(?:,(?=[^\\(]*\\))))*))\\)|)"),CHILD:RegExp("^:(only|nth|last|first)-child(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),POS:RegExp(":(nth|eq|gt|lt|first|last|even|odd)(?:\\((\\d*)\\)|)(?=[^-]|$)","ig"),needsContext:/^[\x20\t\r\n\f]*[>+~]|:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\)|)(?=[^-]|$)/i},O={},P=[],Q={},R=[],B=function(a){a.sizzleFilter=!0;return a},s=function(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}},Y=function(a){return function(b){var d=b.nodeName.toLowerCase();return("input"===d||"button"===d)&&b.type===a}},z=function(a){var b=!1,d=q.createElement("div");try{b=
a(d)}catch(c){}return b},ia=z(function(a){a.innerHTML="<select></select>";a=typeof a.lastChild.getAttribute("multiple");return"boolean"!==a&&"string"!==a}),ja=z(function(a){a.id=v+0;a.innerHTML="<a name='"+v+"'></a><div name='"+v+"'></div>";i.insertBefore(a,i.firstChild);var b=q.getElementsByName&&q.getElementsByName(v).length===2+q.getElementsByName(v+0).length;n=!q.getElementById(v);i.removeChild(a);return b}),ka=z(function(a){a.appendChild(q.createComment(""));return 0===a.getElementsByTagName("*").length}),
la=z(function(a){a.innerHTML="<a href='#'></a>";return a.firstChild&&"undefined"!==typeof a.firstChild.getAttribute&&"#"===a.firstChild.getAttribute("href")}),Z=z(function(a){a.innerHTML="<div class='hidden e'></div><div class='hidden'></div>";if(!a.getElementsByClassName||0===a.getElementsByClassName("e").length)return!1;a.lastChild.className="e";return 1!==a.getElementsByClassName("e").length}),m=function(a,b,d,c){var d=d||[],b=b||q,e,g,j,f,h=b.nodeType;if(1!==h&&9!==h)return[];if(!a||"string"!==
typeof a)return d;j=S(b);if(!j&&!c&&(e=ea.exec(a)))if(f=e[1])if(9===h)if((g=b.getElementById(f))&&g.parentNode){if(g.id===f)return d.push(g),d}else return d;else{if(b.ownerDocument&&(g=b.ownerDocument.getElementById(f))&&ma(b,g)&&g.id===f)return d.push(g),d}else{if(e[2])return F.apply(d,C.call(b.getElementsByTagName(a),0)),d;if((f=e[3])&&Z&&b.getElementsByClassName)return F.apply(d,C.call(b.getElementsByClassName(f),0)),d}return T(a,b,d,c,j)},l=m.selectors={cacheLength:50,match:D,order:["ID","TAG"],
attrHandle:{},createPseudo:B,find:{ID:n?function(a,b,d){if("undefined"!==typeof b.getElementById&&!d)return(a=b.getElementById(a))&&a.parentNode?[a]:[]}:function(a,b,d){if("undefined"!==typeof b.getElementById&&!d)return(b=b.getElementById(a))?b.id===a||"undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id").value===a?[b]:H:[]},TAG:ka?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a)}:function(a,b){var d=b.getElementsByTagName(a);if("*"===a){for(var c,
e=[],g=0;c=d[g];g++)1===c.nodeType&&e.push(c);return e}return d}},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(G,"");a[3]=(a[4]||a[5]||"").replace(G,"");"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1]?(a[2]||m.error(a[0]),a[3]=+(a[3]?a[4]+(a[5]||1):2*("even"===a[2]||"odd"===a[2])),a[4]=+(a[6]+a[7]||"odd"===
a[2])):a[2]&&m.error(a[0]);return a},PSEUDO:function(a){var b,d=a[4];if(D.CHILD.test(a[0]))return null;if(d&&(b=X.exec(d))&&b.pop())a[0]=a[0].slice(0,b[0].length-d.length-1),d=b[0].slice(0,-1);a.splice(2,3,d||a[3]);return a}},filter:{ID:n?function(a){a=a.replace(G,"");return function(b){return b.getAttribute("id")===a}}:function(a){a=a.replace(G,"");return function(b){return(b="undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id"))&&b.value===a}},TAG:function(a){if("*"===a)return function(){return!0};
a=a.replace(G,"").toLowerCase();return function(b){return b.nodeName&&b.nodeName.toLowerCase()===a}},CLASS:function(a){var b=O[a];b||(b=O[a]=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),P.push(a),P.length>l.cacheLength&&delete O[P.shift()]);return function(a){return b.test(a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}},ATTR:function(a,b,d){return!b?function(b){return null!=m.attr(b,a)}:function(c){var c=m.attr(c,a),e=c+"";if(null==c)return"!="===
b;switch(b){case "=":return e===d;case "!=":return e!==d;case "^=":return d&&0===e.indexOf(d);case "*=":return d&&-1<e.indexOf(d);case "$=":return d&&e.substr(e.length-d.length)===d;case "~=":return-1<(" "+e+" ").indexOf(d);case "|=":return e===d||e.substr(0,d.length+1)===d+"-"}}},CHILD:function(a,b,d,e){if("nth"===a){var c=V++;return function(a){var b,x=0,g=a;if(1===d&&0===e)return!0;if((b=a.parentNode)&&(b[v]!==c||!a.sizset)){for(g=b.firstChild;g&&!(1===g.nodeType&&(g.sizset=++x,g===a));g=g.nextSibling);
b[v]=c}a=a.sizset-e;return 0===d?0===a:0===a%d&&0<=a/d}}return function(b){var d=b;switch(a){case "only":case "first":for(;d=d.previousSibling;)if(1===d.nodeType)return!1;if("first"===a)return!0;d=b;case "last":for(;d=d.nextSibling;)if(1===d.nodeType)return!1;return!0}}},PSEUDO:function(a,b,d,e){var c=l.pseudos[a]||l.pseudos[a.toLowerCase()];c||m.error("unsupported pseudo: "+a);return!c.sizzleFilter?c:c(b,d,e)}},pseudos:{not:B(function(a,b,d){var c=$(a.replace(L,"$1"),b,d);return function(a){return!c(a)}}),
enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},parent:function(a){return!l.pseudos.empty(a)},empty:function(a){for(var b,a=a.firstChild;a;){if("@"<a.nodeName||3===(b=a.nodeType)||4===b)return!1;a=a.nextSibling}return!0},contains:B(function(a){return function(b){return-1<
(b.textContent||b.innerText||U(b)).indexOf(a)}}),has:B(function(a){return function(b){return 0<m(a,b).length}}),header:function(a){return ga.test(a.nodeName)},text:function(a){var b,d;return"input"===a.nodeName.toLowerCase()&&"text"===(b=a.type)&&(null==(d=a.getAttribute("type"))||d.toLowerCase()===b)},radio:s("radio"),checkbox:s("checkbox"),file:s("file"),password:s("password"),image:s("image"),submit:Y("submit"),reset:Y("reset"),button:function(a){var b=a.nodeName.toLowerCase();return"input"===
b&&"button"===a.type||"button"===b},input:function(a){return ha.test(a.nodeName)},focus:function(a){var b=a.ownerDocument;return a===b.activeElement&&(!b.hasFocus||b.hasFocus())&&!(!a.type&&!a.href)},active:function(a){return a===a.ownerDocument.activeElement}},setFilters:{first:function(a,b,d){return d?a.slice(1):[a[0]]},last:function(a,b,d){b=a.pop();return d?a:[b]},even:function(a,b,d){for(var b=[],d=d?1:0,c=a.length;d<c;d+=2)b.push(a[d]);return b},odd:function(a,b,d){for(var b=[],d=d?0:1,c=a.length;d<
c;d+=2)b.push(a[d]);return b},lt:function(a,b,d){return d?a.slice(+b):a.slice(0,+b)},gt:function(a,b,d){return d?a.slice(0,+b+1):a.slice(+b+1)},eq:function(a,b,d){b=a.splice(+b,1);return d?a:b}}};l.setFilters.nth=l.setFilters.eq;l.filters=l.pseudos;la||(l.attrHandle={href:function(a){return a.getAttribute("href",2)},type:function(a){return a.getAttribute("type")}});ja&&(l.order.push("NAME"),l.find.NAME=function(a,b){if("undefined"!==typeof b.getElementsByName)return b.getElementsByName(a)});Z&&(l.order.splice(1,
0,"CLASS"),l.find.CLASS=function(a,b,d){if("undefined"!==typeof b.getElementsByClassName&&!d)return b.getElementsByClassName(a)});try{C.call(i.childNodes,0)[0].nodeType}catch(qa){C=function(a){for(var b,d=[];b=this[a];a++)d.push(b);return d}}var S=m.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1},ma=m.contains=i.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:i.contains?function(a,b){var d=9===a.nodeType?a.documentElement:
a,c=b.parentNode;return a===c||!(!c||!(1===c.nodeType&&d.contains&&d.contains(c)))}:function(a,b){for(;b=b.parentNode;)if(b===a)return!0;return!1},U=m.getText=function(a){var b,d="",c=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)d+=U(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[c];c++)d+=U(b);return d};m.attr=function(a,b){var d;(d=S(a))||(b=b.toLowerCase());return l.attrHandle[b]?l.attrHandle[b](a):
ia||d?a.getAttribute(b):(d=a.getAttributeNode(b))?"boolean"===typeof a[b]?a[b]?b:null:d.specified?d.value:null:null};m.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};[0,0].sort(function(){return W=0});i.compareDocumentPosition?f=function(a,b){return a===b?(A=!0,0):(!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition:a.compareDocumentPosition(b)&4)?-1:1}:(f=function(a,b){if(a===b)return A=!0,0;if(a.sourceIndex&&b.sourceIndex)return a.sourceIndex-
b.sourceIndex;var d,c,e=[],g=[];d=a.parentNode;c=b.parentNode;var f=d;if(d===c)return h(a,b);if(d){if(!c)return 1}else return-1;for(;f;)e.unshift(f),f=f.parentNode;for(f=c;f;)g.unshift(f),f=f.parentNode;d=e.length;c=g.length;for(f=0;f<d&&f<c;f++)if(e[f]!==g[f])return h(e[f],g[f]);return f===d?h(a,g[f],-1):h(e[f],b,1)},h=function(a,b,d){if(a===b)return d;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1});m.uniqueSort=function(a){var b,d=1;if(f&&(A=W,a.sort(f),A))for(;b=a[d];d++)b===
a[d-1]&&a.splice(d--,1);return a};var $=m.compile=function(e,b,d){var g,f,h=Q[e];if(h&&h.context===b)return h;var j,I=[];g=0;for(var k=X.exec(e),p=!k.pop()&&!k.pop(),r=p&&e.match(M)||[""],i=l.preFilter,w=l.filter,u=!d&&b!==q;null!=(j=r[g])&&p;g++){I.push(h=[]);for(u&&(j=" "+j);j;){p=!1;if(k=J.exec(j))j=j.slice(k[0].length),p=h.push({part:k.pop().replace(L," "),captures:k});for(f in w)if((k=D[f].exec(j))&&(!i[f]||(k=i[f](k,b,d))))j=j.slice(k.shift().length),p=h.push({part:f,captures:k});if(!p)break}}p||
m.error(e);for(f=0;g=I[f];f++){h=I;j=f;k=b;p=d;i=r=void 0;for(w=0;r=g[w];w++)l.relative[r.part]?i=a(i,l.relative[r.part],k):(r.captures.push(k,p),i=c(i,l.filter[r.part].apply(null,r.captures)));h[j]=i}h=Q[e]=function(a,b){for(var d,c=0;d=I[c];c++)if(d(a,b))return!0;return!1};h.context=b;h.runs=h.dirruns=0;R.push(e);R.length>l.cacheLength&&delete Q[R.shift()];return h};m.matches=function(a,b){return m(a,null,null,b)};m.matchesSelector=function(a,b){return 0<m(b,null,null,[a]).length};var T=function(a,
b,d,c,f){var a=a.replace(L,"$1"),h,j,i,k,p,r,q;k=a.match(M);i=a.match(da);p=b.nodeType;if(D.POS.test(a)){h=a;var w,v,n,t,s;i=0;p=k.length;r=D.POS;q=RegExp("^"+r.source+"(?![\\x20\\t\\r\\n\\f])","i");for(var z=function(){for(var a=1,b=arguments.length-2;a<b;a++)arguments[a]===H&&(w[a]=H)};i<p;i++){r.exec("");h=k[i];f=[];a=0;for(n=c;w=r.exec(h);)if(s=r.lastIndex=w.index+w[0].length,s>a){j=h.slice(a,w.index);a=s;t=[b];J.test(j)&&(n&&(t=n),n=c);if(v=fa.test(j))j=j.slice(0,-5).replace(J,"$&*");1<w.length&&
w[0].replace(q,z);s=j;var y=w[1],B=w[2],A=void 0,E=l.setFilters[y.toLowerCase()];E||m.error(y);if(s||!(A=n))u(s||"*",t,A=[],n);n=0<A.length?E(A,B,v):[]}n?(f=f.concat(n),(j=h.slice(a))&&")"!==j?J.test(j)?u(j,f,d,c):m(j,b,d,c?c.concat(n):n):F.apply(d,f)):m(h,b,d,c)}return 1===p?d:m.uniqueSort(d)}if(c)h=C.call(c,0);else if(k&&1===k.length){if(1<i.length&&9===p&&!f&&(k=D.ID.exec(i[0]))){b=l.find.ID(k[1],b,f)[0];if(!b)return d;a=a.slice(i.shift().length)}j=(k=N.exec(i[0]))&&!k.index&&b.parentNode||b;q=
i.pop();p=q.split(":not")[0];c=0;for(i=l.order.length;c<i;c++)if(r=l.order[c],k=D[r].exec(p))if(h=l.find[r]((k[1]||"").replace(G,""),j,f),null!=h){p===q&&((a=a.slice(0,a.length-q.length)+p.replace(D[r],""))||F.apply(d,C.call(h,0)));break}}if(a){j=$(a,b,f);g=j.dirruns++;null==h&&(h=l.find.TAG("*",N.test(a)&&b.parentNode||b));for(c=0;k=h[c];c++)e=j.runs++,j(k,b)&&d.push(k)}return d};if(q.querySelectorAll){var aa,na=T,oa=/'|\\/g,pa=/\=[\x20\t\r\n\f]*([^'"\]]*)[\x20\t\r\n\f]*\]/g,t=[],E=[":active"],K=
i.matchesSelector||i.mozMatchesSelector||i.webkitMatchesSelector||i.oMatchesSelector||i.msMatchesSelector;z(function(a){a.innerHTML="<select><option selected></option></select>";a.querySelectorAll("[selected]").length||t.push("\\[[\\x20\\t\\r\\n\\f]*(?:checked|disabled|ismap|multiple|readonly|selected|value)");a.querySelectorAll(":checked").length||t.push(":checked")});z(function(a){a.innerHTML="<p test=''></p>";a.querySelectorAll("[test^='']").length&&t.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:\"\"|'')");
a.innerHTML="<input type='hidden'>";a.querySelectorAll(":enabled").length||t.push(":enabled",":disabled")});t=t.length&&RegExp(t.join("|"));T=function(a,b,c,e,f){if(!e&&!f&&(!t||!t.test(a)))if(9===b.nodeType)try{return F.apply(c,C.call(b.querySelectorAll(a),0)),c}catch(g){}else if(1===b.nodeType&&"object"!==b.nodeName.toLowerCase()){var h=b.getAttribute("id"),i=h||v,k=N.test(a)&&b.parentNode||b;h?i=i.replace(oa,"\\$&"):b.setAttribute("id",i);try{return F.apply(c,C.call(k.querySelectorAll(a.replace(M,
"[id='"+i+"'] $&")),0)),c}catch(l){}finally{h||b.removeAttribute("id")}}return na(a,b,c,e,f)};K&&(z(function(a){aa=K.call(a,"div");try{K.call(a,"[test!='']:sizzle"),E.push(l.match.PSEUDO.source,l.match.POS.source,"!=")}catch(b){}}),E=RegExp(E.join("|")),m.matchesSelector=function(a,b){b=b.replace(pa,"='$1']");if(!S(a)&&!E.test(b)&&(!t||!t.test(b)))try{var c=K.call(a,b);if(c||aa||a.document&&11!==a.document.nodeType)return c}catch(e){}return 0<m(b,null,null,[a]).length})}y.ReadSpeaker.Sizzle=m})(window);
ReadSpeaker.lib.RSLib=function(){var y={core_pnum:function(){return/[\-+]?(?:\d*\.|)\d+(?:[eE][\-+]?\d+|)/.source},rposition:function(){return/^(top|right|bottom|left)$/},rmargin:function(){return/^margin/},rnumsplit:function(){return RegExp("^("+this.core_pnum+")(.*)$","i")},rnumnonpx:function(){return RegExp("^("+this.core_pnum+")(?!px)[a-z%]+$","i")},rmsPrefix:function(){return/^-ms-/},rdashAlpha:function(){return/-([\da-z])/gi}},H={_formatRet:function(a){return a.length?1==a.length?a[0].length&&
"object"===typeof a[0]&&!a[0].tagName?a[0][0]:a[0]:a:[]},get:function(a){return"object"==typeof a?a:document.getElementById(a)||this._formatRet(window.ReadSpeaker.Sizzle(a))},findIn:function(a,c){"string"===typeof a&&(a=this.get(a));return this._formatRet(window.ReadSpeaker.Sizzle(c,a))},closest:function(a,c){var e=!1,g=null,f=null,g=null,h=a;"string"===typeof a&&(h=this.get(a));g=$rs.findIn(h.parentNode,c);if(g===h)return h;for(;!e&&h!==document.body;){f=h.parentNode;g=h.parentNode.parentNode;if((g=
$rs.findIn(g,c))&&g===f){e=!0;break}else if(g&&$rs.isArray(g)&&g.length)for(var h=0,n=g.length;h<n;h++)if(g[h]&&g[h]===f){e=!0;g=g[h];break}h=f}if(e)return g},getAttr:function(a,c){"string"===typeof a&&(a=this.get(a));if("style"===c)return a.style.cssText.toLowerCase()||void 0;if(a.attrName)return a.attrName;if(a.getAttribute)return a.getAttribute(c)},setAttr:function(a,c,e){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var g=0,f=a.length;g<f;g++)"style"===c?a[g].style.cssText=
e:a[g].attrName?a[g].attrName=e:a[g].setAttribute&&a[g].setAttribute(c,e);return e},regEvent:function(a,c,e){var g,f;"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var h=0,n=a.length;h<n;h++)f=a[h].window?document.documentElement:a[h],g=this.getAttr(f,"data-rsevent-id")||"rs_"+Math.round(1E6*Math.random()),this.setAttr(f,"data-rsevent-id",g),u.push(g,c,e),(!u.store[g]||!(u.store[g][c]&&1<u.store[g][c].length))&&_addEvent(a[h],c,u.dispatch)},unregEvent:function(a,c,e){var g;"string"===
typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var f=0,h=a.length;f<h;f++)g=a[f].window?document.documentElement:a[f],g=this.getAttr(g,"data-rsevent-id"),e?(g=u.pop(g,c,e))||_removeEvent(a[f],c,u.dispatch):_removeEvent(a[f],c,u.dispatch)},fireEvent:function(){return!1},width:function(a){"string"===typeof a&&(a=this.get(a));return _getSize(a,"width")},height:function(a){"string"===typeof a&&(a=this.get(a));return _getSize(a,"height")},innerWidth:function(a){"string"===typeof a&&(a=this.get(a));
var c=parseFloat(_getCss(a,"border-left-width"))+parseFloat(_getCss(a,"border-right-width"));return _getSize(a,"width")-c},innerHeight:function(a){"string"===typeof a&&(a=this.get(a));var c=parseFloat(_getCss(a,"border-top-width"))+parseFloat(_getCss(a,"border-bottom-width"));return _getSize(a,"height")-c},outerWidth:function(a,c){"string"===typeof a&&(a=this.get(a));if(a&&a.style){var e=c?parseFloat(_getCss(a,"margin-left"))+parseFloat(_getCss(a,"margin-right")):0;return _getSize(a,"width")+e}return null},
outerHeight:function(a,c){"string"===typeof a&&(a=this.get(a));if(a&&a.style){var e=c?parseFloat(_getCss(a,"margin-top"))+parseFloat(_getCss(a,"margin-bottom")):0;return _getSize(a,"height")+e}return null},offsetParent:function(a){"string"===typeof a&&(a=this.get(a));for(var c=/absolute|relative|fixed/i;a!==document.body&&!(a=a.parentNode,a.style&&c.test(_getCss(a,"position"))););return a||document.body},offset:function(a){"string"===typeof a&&(a=this.get(a));var c=document.body,e=document.defaultView||
window,g=document.documentElement,f=document.createElement("div");if(a===document.body)return a=c.offsetTop,f=c.offsetLeft,/explorer/i.test(rspkr.c.data.browser.name)&&8>rspkr.c.data.browser.version||(a+=parseFloat(_getCss(c,"marginTop"))||0,f+=parseFloat(_getCss(c,"marginLeft"))||0),{top:a,left:f};f.style.paddingLeft=f.style.width="1px";c.appendChild(f);var h=2==f.offsetWidth;c.removeChild(f);var f=a.getBoundingClientRect(),n=g.clientTop||c.clientTop||0,q=g.clientLeft||c.clientLeft||0,i=e.pageYOffset||
h&&g.scrollTop||c.scrollTop,e=e.pageXOffset||h&&g.scrollLeft||c.scrollLeft;rspkr.basicMode&&(a===c&&i&&!f.top)&&(f.top=-i);rspkr.basicMode&&(a===c&&e&&!f.left)&&(f.left=-e);return{top:f.top+i-n,left:f.left+e-q}},absOffset:function(a){return this.offset(a)},position:function(a){"string"===typeof a&&this.get(a);return!1},scrollLeft:function(a,c){"string"===typeof a&&(a=this.get(a));return _scrollXY("scrollLeft","pageXOffset",a,c)},scrollTop:function(a,c){"string"===typeof a&&(a=this.get(a));return _scrollXY("scrollTop",
"pageYOffset",a,c)},addClass:function(a,c){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var e,g=0,f=a.length;g<f;g++)e=_trim(a[g].className+" "+c).replace(/ {2,}/g," ").split(" "),a[g].className=e.join(" ")},removeClass:function(a,c){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var e,g=0,f=a.length;g<f;g++){e=_trim(c).replace(/ {2,}/g," ");newClassName=_trim(a[g].className);this.isArray(e)||(e=e.split(" "));for(var h=0,n=e.length;h<n;h++)newClassName=newClassName.replace(RegExp("\\b"+
e[h]+"\\b","gi"),"");a[g].className=_trim(newClassName).replace(/ {2,}/g," ")}},hasClass:function(a,c){"string"===typeof a&&(a=this.get(a));if(!a||this.isArray(a)&&!a.length)return!1;for(var e=a.className.split(" "),g=0,f=e.length;g<f;g++)if(e[g]==c)return!0;return!1},css:function(a,c,e){"string"===typeof a&&(a=this.get(a));if("object"==typeof c||e){var g={};"string"===typeof c?g[_camelCase(c)]=e:g=c;for(var f in g)g.hasOwnProperty(f)&&(a.style[_camelCase(f)]=g[f])}else return _getCss(a,_camelCase(c))},
isVisible:function(a){for(;a!==document.body;){if("none"===this.css(a,"display"))return!1;a=a.parentNode}return!0},addStyleRule:function(a,c,e){e="string"==typeof e?document.styleSheets[e]||document.getElementById(e):e;e.addRule?e.addRule(a,c):e.sheet.insertRule&&e.sheet.insertRule(a+" {"+c+"}",e.sheet.cssRules.length)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},rsid:function(a){if(""==this.getAttr(a,"data-rsid")||void 0==this.getAttr(a,"data-rsid")){var c=ReadSpeaker.rsidCount++;
this.setAttr(a,"data-rsid",c)}return this.getAttr(a,"data-rsid")},detach:function(a){return a.parentNode.removeChild(a)},convertEvent:function(a,c){var a=a||window.event,e=new ReadSpeaker.lib.Facade.RSEvent;e.pageX=a.pageX||a.clientX+$rs.scrollLeft(document);e.pageY=a.pageY||a.clientY+$rs.scrollTop(document);e.screenX=a.screenX;e.screenY=a.screenY;e.clientX=a.clientX;e.clientY=a.clientY;e.target=a.currentTarget||c;e.type=a.type;e.keyCode=a.keyCode;e.targetTouches=a.targetTouches;e.originalEvent=a;
return e},clone:function(a,c,e){return a.cloneNode(e||!1)},camel:function(a){return _camelCase(a)},remove:function(){return jQuery(elm).remove()},replaceWith:function(a,c){return _formatRet(jQuery(a).replaceWith(c))},focus:function(a,c){void 0!==c?this.focusIn(a,c):(a=this.get(a),this.isArray(a)&&0<a.length?a[0].focus?a[0].focus():a[0].setActive&&a[0].setActive():a.focus?a.focus():a.setActive&&a.setActive())},focusIn:function(a,c){a=this.get(a);if(this.isArray(a)&&0<a.length)for(var e=0;e<a.length;e++)void 0!==
c&&_addEvent(a[e],"focus",c);else void 0!==c&&_addEvent(a,"focus",c)},focusOut:function(a,c){a=this.get(a);if(this.isArray(a)&&0<a.length)for(var e=0;e<a.length;e++)void 0!==c&&_addEvent(a[e],"blur",c);else void 0!==c&&_addEvent(a,"blur",c)}},u=null;_getWindow=function(a){return null!=a&&a==a.window?a:9===a.nodeType?a.defaultView||a.parentWindow:!1};_camelCase=function(a){return a.replace(y.rmsPrefix(),"ms-").replace(y.rdashAlpha(),_fcamelCase)};_fcamelCase=function(a,c){return(c+"").toUpperCase()};
_trim=function(a){return a.replace(/^ +/,"").replace(/ +$/,"")};_getCss=window.getComputedStyle?function(a,c){return window.getComputedStyle(a,null)[_camelCase(c)]||!1}:function(a,c){var e,g,f=a.currentStyle&&a.currentStyle[c],h=a.style;null==f&&(h&&h[c])&&(f=h[c]);if(y.rnumnonpx().test(f)&&!y.rposition().test(c)){e=h.left;if(g=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;h.left="fontSize"===c?"1em":f;f=h.pixelLeft+"px";h.left=e;g&&(a.runtimeStyle.left=g)}return""===
f?"auto":f};_getSize=function(a,c){var e="width"==c?"Width":"Height";if(a!==window&&a!==document){e=a["offset"+e];if(isNaN(e)||!e)e=_getCss(a,c);isNaN(e);return parseInt(e)}try{if(a===window)return window["inner"+e]||document.documentElement["client"+e]||document.body["client"+e];if(a===document)return document.body["client"+e]}catch(g){return rspkr.log("[RSLib._getSize] Error: "+g.message,3),0}};_scrollXY=function(a,c,e,g){var f=/X/.test(c),h=_getWindow(e);if(void 0===g)return h?c in h?h[c]:h.document.documentElement[a]||
document&&document.body&&document.body[a]:e[a];h?h.scrollTo(!f?g:$rs.scrollLeft(h),f?g:$rs.scrollTop(h)):e[a]=g};_addEvent=document.addEventListener?function(a,c,e){a.addEventListener&&a.addEventListener(c,e,!1)}:function(a,c,e){a.attachEvent&&a.attachEvent("on"+c,function(c){e(c,a)})};_removeEvent=document.removeEventListener?function(a,c,e){a.removeEventListener&&a.removeEventListener(c,e,!1)}:function(a,c,e){a.detachEvent&&a.detachEvent("on"+c,e)};return{meta:{revision:"1728"},init:function(){window.ReadSpeaker.Sizzle?
(u=ReadSpeaker.lib.Facade.eq,ReadSpeaker.lib.Facade.adapterInit(H),ReadSpeaker.log("[rspkr.l.RSLib] Initialized."),rspkr.Common.dispatchEvent("onAdapterReady")):ReadSpeaker.log("[rspkr.l.RSLib] Error, Sizzle unavailable.",3)}}}();
