<?php
/**
 * @file
 * Install file.
 */

/**
 * Enable "Send e-mail as HTML" option for each existing webform.
 */
function wim_webform_update_7000(&$sandbox) {
  db_update('webform_emails')
    ->fields(array('html' => 1))
    ->execute();
}

/**
 * Use antibot instead honeypot.
 */
function wim_webform_update_7001(&$sandbox) {
  module_enable(array('antibot'));
  features_revert_module('wim_webform');
}
