<?php

/**
 * @file
 * Code for the WIM Webform feature.
 */

include_once 'wim_webform.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function wim_webform_form_webform_client_form_alter(&$form, $form_state) {
  $form['#attributes']['novalidate'] = 'novalidate';

  $form_sets = array(
    'radios',
    'checkboxes',
    'date',
    'webform_time',
    'webform_grid',
  );

  foreach ($form['submitted'] as &$element) {
    if (is_array($element) && in_array($element['#type'], $form_sets) && $element['#title_display'] !== 'none') {

      // Check if element is required and add * to fieldset later.
      $required = '';
      if ($element['#required'] == 1) {
        $required = '&nbsp' . $required = '&nbsp' . theme('form_required_marker');
      }

      // Wrap elements in fieldsets for accessibility.
      $element['#prefix'] = '<fieldset class="webform-container">';
      $element['#prefix'] .= '<legend class="webform-container-legend">' . $element['#title'] . $required . '</legend>';
      $element['#suffix'] = '</fieldset>';
      $element['#title_display'] = 'invisible';
    }
    elseif (isset($element['#title_display']) && $element['#title_display'] === 'none') {

      // Wrapping in fieldsets shoudn't happen if component doesn't have a
      // title, but incorrect labels should still be removed.
      $element['#title_display'] = 'invisible';
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function wim_webform_form_alter(&$form, $form_state) {
  // Alter the file upload component of webforms.
  if ($form['#form_id'] == 'webform_component_edit_form' && $form['type']['#value'] == 'file') {
    global $user;

    // Set default file to private.
    // Only webmasters & administrators can change this.
    if (
      !in_array('administrator', $user->roles) &&
      !in_array('webmaster', $user->roles) &&
      !empty(variable_get('file_private_path'))
    ) {
      $form['extra']['scheme']['#default_value'] = 'private';
      $form['extra']['scheme']['#disabled'] = TRUE;
      $form['extra']['scheme']['#type'] = 'hidden';
    }
    elseif (!empty(variable_get('file_private_path'))) {
      $form['extra']['scheme']['#default_value'] = 'private';
    }
  }
}

function wim_webform_mail_alter(&$message) {
  // Alter the message of webforms to add attachment.
  if ($message['key'] == 'submission' && $message['module'] = 'webform') {
    // Check if sending attachments is enabled for the form.
    if (
      !empty($message['params']) &&
      !empty($message['params']['node']->field_send_attachments_with_emai) &&
      $message['params']['node']->field_send_attachments_with_emai[LANGUAGE_NONE]['0']['value'] == '1'
    ) {
      // Loop through all the webform components.
      foreach ($message['params']['node']->webform['components'] as $component) {
        // Get all the webform components with fieldtype file.
        if (
          $component['type'] == 'file' &&
          isset($message['params']['submission']->data[$component['cid']])
        ) {
          // Load the file.
          $file = file_load($message['params']['submission']->data[$component['cid']][0]);

          // Attach the file to the email.
          $message['params']['attachments'][] = array(
            'filepath' => $file->uri,
          );
        }
      }
    }
  }
}