<?php
/**
 * @file
 * WIM CVDR main module file.
 */

/**
 * Implements hook_menu().
 */
function wim_cvdr_menu() {
  $items = [];

  $items['admin/config/services/cvdr'] = [
    'title' => 'WIM CVDR',
    'description' => 'Configuration for connecting with CVDR.',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['_wim_cvdr_admin_page'],
    'access arguments' => ['administer blocks'],
    'type' => MENU_NORMAL_ITEM,
    'file' => 'wim_cvdr.admin.inc',
  ];

  return $items;
}

/**
 * Implements hook_block_info().
 */
function wim_cvdr_block_info() {
  $blocks = [];
  $subjects = _wim_cvdr_retrieve_subjects();

  // Create a seperate block for each subject.
  foreach ($subjects as $subject) {
    // Create nice machine name based on subject name.
    $machine_name = str_replace('-', '_', drupal_html_class($subject));
    $blocks[md5('wim_cvdr_' . $machine_name)] = [
      'info' => t('CVDR: !subject', ['!subject' => $subject]),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ];
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function wim_cvdr_block_view($delta = '') {
  $block = [];

  $subjects = _wim_cvdr_retrieve_subjects();
  foreach ($subjects as $subject) {
    // Create nice machine name based on subject name.
    $machine_name = str_replace('-', '_', drupal_html_class($subject));

    // Check if block is current subject.
    if ($delta === md5('wim_cvdr_' . $machine_name)) {
      // Render subject block.
      $block['subject'] = trim(str_replace([
        '(URL-0)',
        '(URL-1)',
      ], '', $subject));

      // Build the links to the CVDR items.
      $items = _wim_cvdr_retrieve_items($subject);

      // Sort the items alphabetically.
      sort($items);

      foreach ($items as $item) {
        $list_items[] = l($item['title'], $item['url'],
          ['attributes' => ['target' => '_blank']]);
      }

      $block['content'] = theme('item_list', [
        'items' => $list_items,
        'title' => '',
        'type' => 'ul',
        'attributes' => [
          'class' => ['cvdr-wim', drupal_html_class($subject)],
        ],
      ]);
    }
  }

  // Add JS.
  drupal_add_js([
    'wim_cvdr' => [
      'maxItems' => variable_get('wim_cvdr_max_visible', 5) - 1,
    ],
  ], 'setting');
  drupal_add_js(
    drupal_get_path('module', 'wim_cvdr') . '/wim_cvdr.js', [
      'type' => 'file',
      'scope' => 'footer',
    ]
  );

  return $block;
}

/**
 * Get the subjects available from the webservice.
 *
 * @return array
 *   containing the subjects.
 */
function _wim_cvdr_retrieve_subjects() {
  return array_keys(_wim_cvdr_retrieve_elements());
}

/**
 * Get all items from the webservice.
 *
 * @param string $key
 *   Indicating which block to render.
 *
 * @return array
 *   Containing all items.
 */
function _wim_cvdr_retrieve_items($key = '') {

  $items = _wim_cvdr_retrieve_elements();

  if (empty($items)) {
    return [];
  }

  // Return specific items if requested.
  if (!empty($key) && array_key_exists($key, $items)) {
    return $items[$key];
  }
  elseif (!empty($key) && !array_key_exists($key, $items)) {
    // Block could not be rendered.
    return [];
  }

  // Return all items.
  return $items;
}

/**
 * Retrieve the elements available from the webservice.
 *
 * @return array
 *   containing the elements.
 */
function _wim_cvdr_retrieve_elements() {
  $items = [];

  // Use caching to improve performance.
  if ($cached = cache_get('wim_cvdr_items')) {
    $items = $cached->data;
  }
  // Manual cache clears will trigger the CVDR on page reload.
  else {
    $xmls = _wim_cvdr_read_xml();
    if ($xmls) {
      foreach ($xmls as $id => $xml) {
        $items = array_merge($items, _wim_cvdr_process_xml($xml, $id));
      }

      // Save the cached results to improve performance.
      $expire = REQUEST_TIME + (variable_get('wim_cvdr_cache_time', 60) * 60);
      cache_set('wim_cvdr_items', $items, 'cache', $expire);
    }
  }

  return $items;
}

/**
 * Request the XML from the webservice.
 */
function _wim_cvdr_read_xml() {
  $data = [];
  $xml_urls = _wim_cvdr_get_urls();

  foreach ($xml_urls as $xml_url) {
    if ($xml_url) {
      // Request the XML from the webservice.
      $xml_response = drupal_http_request($xml_url);

      // DIMPACT-26: Check for correct request and response.
      if ($xml_response->code !== '200') {
        // Log error and quit.
        watchdog('WIM CVDR',
          'Could not retrieve XML from !url. Debug: !array',
          [
            '!url' => $xml_url,
            '!array' => print_r($xml_response, TRUE),
          ],
          WATCHDOG_ERROR);
        continue;
      }

      // Check for valid xml.
      libxml_use_internal_errors(TRUE);
      $xml = simplexml_load_string($xml_response->data);
      if (!$xml) {
        watchdog('WIM CVDR',
          'Could not retrieve a valid XML from !url. Debug: !array',
          [
            '!url' => $xml_url,
            '!array' => print_r(libxml_get_errors(), TRUE),
          ],
          WATCHDOG_ERROR);
        libxml_clear_errors();
        continue;
      }

      $data[] = $xml_response->data;
    }
  }

  // Return the XML data.
  return $data;
}

/**
 * Process the XML by creating an array keyed on subject.
 *
 * @param string $xml
 *   The xml in string format.
 *
 * @return array
 *   With items keyed on subject and sorted.
 */
function _wim_cvdr_process_xml($xml, $xml_id) {

  $subject_source = !empty(variable_get('wim_cvdr_subject_source')) ?
    variable_get('wim_cvdr_subject_source') : 'overheidrg:onderwerp';
  $items = [];
  libxml_use_internal_errors(TRUE);
  $xml_dom = new DOMDocument();

  if ($xml_dom->loadXML($xml) === FALSE) {
    // Log error and quit.
    watchdog('WIM CVDR',
      'XML is malformed and couldn\'t be properly loaded/parsed. Errors: !message',
      ['!message' => print_r(libxml_get_errors(), TRUE)],
      WATCHDOG_ERROR);
    libxml_clear_errors();

    return $items;
  }

  // Loop through the items in the XML.
  foreach ($xml_dom->getElementsByTagName('gzd') as $item) {
    // Retrieve the needed data by using xpath queries.
    $xpath = new DOMXpath($xml_dom);

    $urlQueryResult = $item->getElementsByTagName('publicatieurl_xhtml');
    $url = ($urlQueryResult instanceof DOMNodeList) ?
      $urlQueryResult->item(0) : NULL;

    $alternativeQueryResult = $xpath->query('.//dcterms:alternative', $item);
    $alternative = ($alternativeQueryResult instanceof DOMNodeList) ?
      $alternativeQueryResult->item(0) : NULL;

    $titleQueryResult = $xpath->query('.//dcterms:title', $item);
    $title = ($titleQueryResult instanceof DOMNodeList) ?
      $titleQueryResult->item(0) : NULL;

    $overheidNs = 'http://standaarden.overheid.nl/cvdr/terms/';
    if ($subject_source == 'overheidrg:onderwerp') {
      $subjectQuery = $item->getElementsByTagNameNS($overheidNs, 'onderwerp');
      $subject = !empty($subjectQuery->item(0)->nodeValue) ?
        $subjectQuery->item(0)->nodeValue : t('Other');
    } 
    else {
      $subjectQueryResult = $xpath->query('.//dcterms:subject', $item);
      $subject = ($subjectQueryResult instanceof DOMNodeList) ?
        $subjectQueryResult->item(0) : t('Other');
    }

    $dateQuery = $item->getElementsByTagNameNS($overheidNs, 'uitwerkingtredingDatum');
    $date = !empty($dateQuery->item(0)->nodeValue) ?
      $dateQuery->item(0)->nodeValue : NULL;

    // Use the official title if this is available.
    if (!empty($alternative->nodeValue)) {
      $title = $alternative;
    }

    // Only proceed if everything is available.
    if (isset($url, $subject, $title)) {
      $url = $url->nodeValue;

      // Check and see if the url is available on https.
      $desiredScheme = "https";
      $parsedRedirectUri = parse_url($url);
      if ($parsedRedirectUri['scheme'] !== $desiredScheme) {
        $parsedUrl = substr_replace($url, $desiredScheme, 0, strlen($parsedRedirectUri['scheme']));
        $stream = stream_context_create(["ssl" => ["capture_peer_cert" => TRUE]]);
        $read = fopen($parsedUrl, "rb", FALSE, $stream);
        $cont = stream_context_get_params($read);
        $var = ($cont["options"]["ssl"]["peer_certificate"]);
        if (!is_null($var)) {
          $url = $parsedUrl;
        }
      }

      $subject = ucfirst($subject->nodeValue) . ' (URL-' . $xml_id . ')';
      $title = $title->nodeValue;

      // Check if no expire date is set or expire date is in the future.
      if (empty($date) || strtotime($date) > REQUEST_TIME) {

        // Save the item keyed by its subject.
        $items[$subject][] = [
          'title' => $title,
          'url' => $url,
        ];
      }
    }
  }

  // Sort items on key (subject) alphabetically.
  ksort($items);

  return $items;
}

/**
 * Fetch XML URLs.
 */
function _wim_cvdr_get_urls() {
  return [
    variable_get('wim_cvdr_url', ''),
    variable_get('wim_cvdr_url_second', ''),
  ];
}

/**
 * Implements hook_cronapi().
 */
function wim_cvdr_cronapi($op, $job = NULL) {
  $items['wim_cvdr_cron'] = [
    'description' => t('Cache CVDR blocks'),
    'rule' => '0 */6 * * *',
  ];
}

/**
 * Implements hook_cron().
 */
function wim_cvdr_cron() {
  $items = [];
  $xmls = _wim_cvdr_read_xml();
  if ($xmls) {
    foreach ($xmls as $id => $xml) {
      $items = array_merge($items, _wim_cvdr_process_xml($xml, $id));
    }

    // Save the cached results to improve performance.
    $expire = REQUEST_TIME + (variable_get('wim_cvdr_cache_time', 60) * 60);
    cache_set('wim_cvdr_items', $items, 'cache', $expire);
  }
}
