<?php
/**
 * @file
 * Code for the WIM Agenda feature.
 */

include_once 'wim_agenda.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function wim_agenda_form_agenda_node_form_alter(&$form, &$form_state, $form_id) {

  // Show the "Announcement type" when Announcement category is selected.
  $form['field_agenda_announcement_type']['#states'] = array(
    'visible' => array(
      'select[name="field_agenda_category[und]"]' => array('value' => 'announcement'),
    ),
  );

}

/**
 * Implements hook_views_pre_build().
 */
function wim_agenda_views_pre_build(&$view) {
  if ($view->name === 'agenda') {
    if ($view->current_display === 'upcoming_agenda' && isset($view->footer['area_text_custom']) && user_access('create agenda content')) {
      // Add link to add new agenda content.
      $agenda_add_link = l(t('Add event'), '/node/add/agenda', array('attributes' => array('class' => array('content-add-button'))));
      $view->footer['area_text_custom']->options['content'] = str_replace('<![CONTENT_IS_REPLACED_IN_CODE]!>', $agenda_add_link, $view->footer['area_text_custom']->options['content']);
    }
  }
}
