<?php
/**
 * @file
 * Code for the ReadSpeaker.
 */

/**
 * Implements hook_menu().
 */
function readspeaker_menu() {
  $items = array();

  $items['admin/config/services/readspeaker'] = array(
    'title' => 'ReadSpeaker',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('readspeaker_settings_form'),
    'access arguments' => array('administer readspeaker'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'readspeaker.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function readspeaker_admin_paths() {
  $paths = array(
    'admin/config/services/readspeaker' => TRUE,
  );

  return $paths;
}

/**
 * Implements hook_permission().
 */
function readspeaker_permission() {
  return array(
    'administer readspeaker' => array(
      'title' => t('Administer Read Speaker'),
      'description' => t('Administer ReadSpeaker settings.'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function readspeaker_theme($existing, $type, $theme, $path) {
  return array(
    'readspeaker' => array(
      'variables' => array(
        'customer_id' => NULL,
        'lang' => NULL,
        'readid' => 'main',
        'url' => 'main',
      ),
      'template' => 'readspeaker',
      'path' => "$path/theme",
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function readspeaker_block_info() {
  $blocks = array();

  $blocks['readspeaker'] = array(
    'info' => t('Read Speaker'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function readspeaker_block_view($delta = '') {
  $block = array();

  if ($delta === 'readspeaker') {
    $block['content'] = 'Block content';
  }

  return $block;
}
