<?php
/**
 * @file
 * Code for the WIM Core feature.
 */

include_once 'wim_core.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function wim_core_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['short'] = array(
    'label' => t('Short'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_image_default_styles().
 */
function wim_core_image_default_styles() {
  $styles = array();

  $styles['teaser'] = array(
    'name' => 'teaser',
    'label' => 'Teaser (150x150)',
    'effects' => array(
      array(
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 150,
          'height' => 150,
        ),
        'weight' => 0,
      ),
    ),
  );

  $styles['teaser_mobile'] = array(
    'name' => 'teaser',
    'label' => 'Teaser mobile (430xAUTO)',
    'effects' => array(
      array(
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 430,
          'height' => '',
          'upscale' => 0,
        ),
        'weight' => 0,
      ),
    ),
  );

  $styles['teaser_mobile_retina'] = array(
    'name' => 'teaser',
    'label' => 'Teaser retina (860xAUTO)',
    'effects' => array(
      array(
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 860,
          'height' => '',
          'upscale' => 0,
        ),
        'weight' => 0,
      ),
    ),
  );

  $styles['list_thumbnail'] = array(
    'name' => 'list_thumbnail',
    'label' => 'List thumbnail (100x100)',
    'effects' => array(
      array(
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 100,
          'height' => 100,
        ),
        'weight' => 1,
      ),
    ),
  );

  $styles['node_thumbnail'] = array(
    'name' => 'node_thumbnail',
    'label' => 'Node thumbnail (532x225)',
    'effects' => array(
      array(
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 532,
          'height' => 225,
        ),
        'weight' => 1,
      ),
    ),
  );

  return $styles;
}
