<?php
/**
 * @file
 * Instalation file.
 */

/**
 * Implements hook_install().
 */
function wim_apachesolr_media_install() {
  variable_set('apachesolr_attachments_tika_path', '/var/lib/tika');
  variable_set('apachesolr_attachments_tika_jar', 'tika-app-1.18.jar');
  variable_set('apachesolr_attachments_filesize_limit', '52428800');
  variable_set('apachesolr_attachments_extract_using', 'tika');
  // Note, this option provides by patch of apachesolr_attachments module:
  // @see: https://www.drupal.org/files/issues/apachesolr-attachments-index-unattached-files-1908484-13.patch.
  variable_set('apachesolr_attachments_entity_bundle_indexing_document', 'seperate');
}

/**
 * Enable indexing of Document file bundle as separate entity.
 */
function wim_apachesolr_media_update_7001() {
  variable_set('apachesolr_attachments_entity_bundle_indexing_document', 'seperate');
}

/**
 * Update Apache Tika app to the 1.18 version.
 */
function wim_apachesolr_media_update_7002() {
  variable_set('apachesolr_attachments_tika_jar', 'tika-app-1.18.jar');
}
